- alias: Dehumidifier - Basement - Toggle
  mode: single

  trigger:
    # Electricity price changes
    - platform: state
      entity_id:
        - sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate

  action:
    - choose:
        # Electricity is below 20p - turn on
        - conditions:
            - condition: numeric_state
              entity_id: sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate
              below: 0.20
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.dehumidifier_basement_switch

        # Electricity is above 20p - turn off
        - conditions:
            - condition: numeric_state
              entity_id: sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate
              above: 0.20
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.dehumidifier_basement_switch
