- alias: Dehumidifier - Basement - Toggle
  mode: single

  trigger:
    # Electricity price changes
    - platform: state
      entity_id:
        - sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate

  action:
    - choose:
        # Electricity is cheap - turn on
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "on"
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.dehumidifier_basement_switch

        # Electricity is expensive - turn off
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "off"
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.dehumidifier_basement_switch
