- alias: Heating - Basement - Schedule
  mode: single

  trigger:
    # Has 15 minutes elapsed?
    - platform: time_pattern
      minutes: /15

  action:
    - choose:
        # Humidity is high
        - conditions:
            - condition: numeric_state
              entity_id: sensor.basement_humidity
              above: 70
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 22
              target:
                entity_id: climate.basement

        # Humidity is not high
        - conditions:
            - condition: numeric_state
              entity_id: sensor.basement_humidity
              below: 70
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.basement
