- alias: Heating - Basement - Schedule
  mode: single

  trigger:
    # Has anyone just come/left home?
    - platform: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - platform: time_pattern
      minutes: /15

  action:
    - choose:
        # Someone is home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "on"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.basement

        # No one is home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 16
              target:
                entity_id: climate.basement
