- alias: Heating - Basement - Schedule
  mode: single

  triggers:
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  action:
    - choose:
        # Basement humidity is higher than 70% and dehumidifier is on
        - conditions:
            - condition: numeric_state
              entity_id: sensor.basement_humidity
              above: 70
            - condition: state
              entity_id: switch.dehumidifier_basement_switch
              state: "on"

          sequence:
            - action: climate.set_temperature
              data:
                temperature: 21
              target:
                entity_id: climate.tado_trv_basement

      # Above conditions not met so default to 18 degrees
      default:
        - action: climate.set_temperature
          data:
            temperature: 18
          target:
            entity_id: climate.tado_trv_basement
