
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

zha:
  device_config:
    00:15:8d:00:02:57:b0:85-11:
      type: "switch"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
