---
- alias: Sensor Low Battery
  trigger:
    - platform: numeric_state
      below: 10
      entity_id:
        - sensor.study_window_battery
    - platform: state
      to: unavailable
      for: 06:00:00
      entity_id:
        - sensor.study_window_battery

  action:
    - action: notify.mobile_app_berties_iphone
      data:
        message: 🔋 The {{ state_attr(trigger.entity_id, 'friendly_name') }} level is {{ trigger.to_state.state }}
