- alias: Heating - Living Room - Schedule
  mode: single

  trigger:
    # Has the state of the schedule just changed
    - platform: state
      entity_id:
        - schedule.living_room_evening
    # Has anyone just come/left home?
    - platform: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - platform: time_pattern
      minutes: /15

  # Living Room window is closed
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_window_opening
      state: "off"

  action:
    - choose:
        # Daytime schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.living_room_evening
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 22
                      target:
                        entity_id: climate.living_room

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 17
                      target:
                        entity_id: climate.living_room

        # Daytime schedule deactivated
        - conditions:
            - condition: state
              entity_id: schedule.living_room_evening
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.living_room
