- alias: Heating - Living Room - Window
  mode: single

  # Window state changes
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.living_room_window_opening

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_window_opening
              state: "on"
          sequence:
            - action: climate.turn_off
              target:
                entity_id: climate.tado_trv_living_room

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_window_opening
              state: "off"
          sequence:
            - choose:
                # Living Room Evening Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.living_room_evening
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 22
                      target:
                        entity_id: climate.tado_trv_living_room

                # Living Room Evening Schedule is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.living_room_evening
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.tado_trv_living_room
