- alias: Lights - Living Room - TV
  mode: single

  triggers:
    # Apple TV Plex client has a status change
    - trigger: state
      entity_id:
        - media_player.plex_plex_for_apple_tv_apple_tv

  condition:
    # Someone is home
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"

  action:
    # If Plex is playing, dim the lights.
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.plex_plex_for_apple_tv_apple_tv
              state: playing
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.living_room
              data:
                kelvin: 2600
                brightness_pct: 30

      # If Plex is not playing, brighten the lights.
      default:
        - action: light.turn_on
          target:
            entity_id: light.living_room
          data:
            kelvin: 2600
            brightness_pct: 100
