- alias: Lights - Living Room - Schedule
  mode: single

  triggers:
    # Is the sun about to set
    - trigger: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 7

    # Is the time 1am
    - trigger: time
      at: "01:00:00"

    # Is the time 5am
    - trigger: time
      at: "05:00:00"

  condition:
    # Someone is home
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"

  action:
    - choose:
        - conditions:
            - condition: time
              after: "14:30:00"
              before: "23:59:00"
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.living_room
              data:
                kelvin: 2600
                brightness_pct: 70

        - conditions:
            - condition: time
              after: "23:59:00"
              before: "04:00:00"
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.living_room

        - conditions:
            - condition: time
              after: "04:00:00"
              before: "06:00:00"
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.living_room
              data:
                rgb_color: [255, 0, 0]
                brightness_pct: 50
