- alias: Living Room - Heating - Home State
  mode: single

  # Home/Away state changes
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home_state

  action:
    - choose:
        # Someone arrived home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "on"
          sequence:
            - choose:
                # Evening Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.living_room_evening
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 22
                      target:
                        entity_id: climate.living_room

                # Evening Schedule is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.living_room_evening
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 17
                      target:
                        entity_id: climate.living_room

        # Everyone left home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.living_room
