- alias: Lights - Landing - Schedule
  mode: single

  triggers:
    # Is the sun about to set
    - trigger: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 5

    # Is the time 9pm
    - trigger: time
      at: "21:00:00"

  condition:
    # Someone is home
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"

  action:
    - choose:
        - conditions:
            - condition: time
              after: "14:30:00"
              before: "21:00:00"
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.hare
              data:
                kelvin: 2600
                brightness_pct: 70

        - conditions:
            - condition: time
              after: "21:00:00"
              before: "06:00:00"
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.hare
