- alias: Bathroom - Heating - Schedule
  mode: single

  # Bathroom schedule changes
  trigger:
    - platform: state
      entity_id:
        - schedule.bathroom_boost

  action:
    - choose:
        # Boost schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.bathroom_boost
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 25
                      target:
                        entity_id: climate.bathroom

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.bathroom

        # Daytime schedule deactivated
        - conditions:
            - condition: state
              entity_id: schedule.bathroom_boost
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.bathroom
