- alias: Bathroom - Heating - Window State
  mode: single

  # Window state changes
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroom_window_opening

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.bathroom_window_opening
              state: "on"
          sequence:
            - choose:
                # Boost is active
                - conditions:
                    - condition: state
                      entity_id: schedule.bathroom_boost
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 25
                      target:
                        entity_id: climate.bathroom

                # Boost is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.bathroom_boost
                      state: "off"
                  sequence:
                    - service: climate.turn_off
                      target:
                        entity_id: climate.bathroom

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.bathroom_window_opening
              state: "off"
          sequence:
            - choose:
                # Boost is active
                - conditions:
                    - condition: state
                      entity_id: schedule.bathroom_boost
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 25
                      target:
                        entity_id: climate.bathroom

                # Boost is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.bathroom_boost
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.bathroom
