- alias: Heating - Bathroom - Schedule
  mode: single

  trigger:
    # Has the state of the schedule just changed
    - platform: state
      entity_id:
        - schedule.bathroom_boost
    # Has 15 minutes elapsed?
    - platform: time_pattern
      minutes: /15

  action:
    - choose:
        # Boost schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.bathroom_boost
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 25
                      target:
                        entity_id: climate.bathroom

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.bathroom

        # Boost schedule is not active
        - conditions:
            - condition: state
              entity_id: schedule.bathroom_boost
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.bathroom
