- alias: Heating - Hallway - Schedule
  mode: single

  triggers:
    # Has the state of the schedule just changed
    - trigger: state
      entity_id:
        - schedule.hallway_daytime
        - schedule.hallway_evening
    # Has anyone just come/left home?
    - trigger: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  # Living Room window is closed
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_window_opening
      state: "off"

  action:
    - choose:
        # No one is home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.hallway

        # Evening schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.hallway_evening
              state: "on"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 22
              target:
                entity_id: climate.hallway

        # Daytime schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.hallway_daytime
              state: "on"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 21
              target:
                entity_id: climate.hallway

      default:
        - action: climate.set_temperature
          data:
            temperature: 19
          target:
            entity_id: climate.hallway
