---
- platform: template
  sensors:
    windows_upstairs:
      friendly_name: Upstairs Windows
      value_template: "{{ is_state('binary_sensor.landing_window_opening', 'on') or is_state('binary_sensor.study_window_opening', 'on') }}"
