- alias: Config - Update, Check & Restart
  mode: single
  trigger:
    - platform: webhook
      allowed_methods:
        - POST
      local_only: false
      webhook_id: "-Z7gIJKDlN9QKCG6poK8q67CT"
  action:
    - action: shell_command.git_pull
    - action: homeassistant.check_config
    - action: homeassistant.restart
