- alias: Octopus - Wheel of Fortune spins
  mode: single

  trigger:
    - platform: numeric_state
      above: 0
      entity_id:
        - sensor.octopus_energy_a_e94ebeba_wheel_of_fortune_spins_electricity
        - sensor.octopus_energy_a_e94ebeba_wheel_of_fortune_spins_gas

  action:
    - action: persistent_notification.create
      data:
        title: Wheel of Fortune spins available
        message: Octopus - Wheel of Fortune spins available
