---
- alias: Hass Startup Notification
  triggers:
    - trigger: homeassistant
      event: shutdown
  action:
    - action: notify.mobile_app_berties_iphone
      data:
        message: 🌶 Home Assistant is shutting down
