---
- alias: Hass Startup Notification
  triggers:
    - trigger: homeassistant
      event: start
  action:
    - action: notify.mobile_app_berties_iphone
      data:
        message: 🌵 Home Assistant has started
