- alias: Home State - Update
  mode: single

  trigger:
    - platform: state
      entity_id:
        - group.family
        - input_boolean.guest_state

  action:
    - choose:
        # Family comes home or guest state is turned on
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.family
                  state: home
                - condition: state
                  entity_id: input_boolean.guest_state
                  state: "on"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.home_state

        # Family leaves home & there are no guests
        - conditions:
            - condition: state
              entity_id: group.family
              state: not_home
            - condition: state
              entity_id: input_boolean.guest_state
              state: "off"
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id:
                  - input_boolean.home_state
