- alias: Home State - Update
  mode: single

  triggers:
    - trigger: state
      entity_id:
        - group.family

  action:
    - choose:
        # Family comes home or guest state is turned on
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.family
                  state: home
          sequence:
            - action: input_boolean.turn_on
              target:
                entity_id: input_boolean.home_state

        # Family leaves home & there are no guests
        - conditions:
            - condition: state
              entity_id: group.family
              state: not_home
          sequence:
            - action: input_boolean.turn_off
              target:
                entity_id:
                  - input_boolean.home_state
