- alias: Homekit Presence - Restart
  mode: single

  trigger:
    - platform: homeassistant
      event: start

  action:
    - parallel:
        - if:
            - condition: state
              entity_id: input_boolean.bertie_present
              state: "on"
          then:
            - action: device_tracker.see
              data:
                dev_id: homekit_bertie
                location_name: "home"
        - if:
            - condition: state
              entity_id: input_boolean.stoof_present
              state: "on"
          then:
            - action: device_tracker.see
              data:
                dev_id: homekit_stoof
                location_name: "home"
        - if:
            - condition: state
              entity_id: input_boolean.housesitter_present
              state: "on"
          then:
            - action: device_tracker.see
              data:
                dev_id: homekit_housesitter
                location_name: "home"
