- alias: Home State - Update
  mode: single

  trigger:
    - platform: state
      entity_id:
        - zone.home
      attribute: persons

  action:
    - choose:
        # home zone has people in it
        - conditions:
            - condition: numeric_state
              entity_id: zone.home
              attribute: persons
              above: 0
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.home_state

        # home zone does *not* have people in it
        - conditions:
            - condition: numeric_state
              entity_id: zone.home
              attribute: persons
              below: 1
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.home_state
