- alias: Homekit Presence - Toggle
  mode: parallel
  max: 10

  trigger:
    - entity_id: input_boolean.bertie_present
      platform: state
    - entity_id: input_boolean.stoof_present
      platform: state

  action:
    - service: device_tracker.see
      data_template:
        dev_id: homekit_{{ trigger.to_state.name }}
        location_name: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
