- alias: Homekit Presence - Toggle
  mode: parallel
  max: 10

  trigger:
    - entity_id: input_boolean.bertie_present
      platform: state
    - entity_id: input_boolean.stoof_present
      platform: state
    - entity_id: input_boolean.housesitter_present
      platform: state

  action:
    - choose:
        # If input_boolean is switched to "on"
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state  == 'on' }}"

          # Set the device_tracker to "home" with the id interpolated from the
          sequence:
            - service: device_tracker.see
              data_template:
                dev_id: homekit_{{ trigger.to_state.name }}
                location_name: "home"

        # If input_boolean is switched to "off"
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state  == 'off' }}"

          # Set the device_tracker to "not_home" with the id interpolated from the trigger
          sequence:
            - service: device_tracker.see
              data_template:
                dev_id: homekit_{{ trigger.to_state.name }}
                location_name: "not_home"
