- alias: Climate Reset
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
    - platform: time
      at: "00:00:00"
  action:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        floor_id:
          - basement
          - ground_floor
          - first_floor
          - attic
