alias: Config - Update, Check & Restart
mode: single
trigger:
  - platform: webhook
    allowed_methods:
      - POST
    local_only: false
    webhook_id: "-Z7gIJKDlN9QKCG6poK8q67CT"
action:
  - service: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.study_corner
