- alias: Config - Update, Check & Reload
  mode: single
  trigger:
    - platform: webhook
      allowed_methods:
        - POST
      local_only: false
      webhook_id: "config_update_reload"
  action:
    - service: shell_command.git_pull
    - service: homeassistant.check_config
    - service: homeassistant.reload_all
