- alias: Dehumidifier - Bedroom - Off
  mode: single
  trigger:
    - platform: state
      entity_id:
        - input_boolean.cheap_electricity
      from: "on"
      to: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.dehumidifier_basement_switch
