- alias: Dehumidifier - Basement - On
  mode: single
  trigger:
    - platform: state
      entity_id:
        - input_boolean.cheap_electricity
      to: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.dehumidifier_basement_switch
