- alias: Cheap Energy
  description: "Determines whether to set the Cheap Electricity switch to on/off"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate
  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate
              above: 0.15
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id:
                  - input_boolean.cheap_electricity
        - conditions:
            - condition: numeric_state
              entity_id: sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate
              below: 0.15
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.cheap_electricity
