- alias: Cheap Energy
  description: "Determines whether to set the Cheap Electricity switch to on/off"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - sensor.octopus_energy_electricity_22l3444132_1610012177566_current_rate
      from:
      to:
  action:
    - choose:
        - conditions:
            - condition: time
              after: "16:00:00"
              before: "19:00:00"
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id:
                  - input_boolean.cheap_electricity
        - conditions:
            - condition: time
              before: "16:00:00"
              after: "19:00:00"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.cheap_electricity
