- alias: Workstation - Off
  mode: single
  trigger:
    - platform: time
      at: "17:30:00"
  action:
    - service: light.turn_off
      target:
        entity_id: switch.study_workstation_switch
