- alias: Workstation - On
  mode: single
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      target:
        entity_id: switch.study_workstation_switch
