- alias: Bedroom - Heating - Schedule
  mode: single

  # Bedroom schedule changes
  trigger:
    - platform: state
      entity_id:
        - schedule.bedroom_daytime

  action:
    - choose:
        # Daytime schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.bedroom_daytime
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.bedroom

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 17
                      target:
                        entity_id: climate.bedroom

        # Daytime schedule deactivated
        - conditions:
            - condition: state
              entity_id: schedule.bedroom_daytime
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.bedroom
