- alias: Bedroom - Heating - Off
  mode: single
  trigger:
    # 3 Hourly Forecast becomes "warm"
    - platform: state
      entity_id: input_boolean.three_hourly_warm
      to: "on"
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.bedroom
