- alias: Bedroom - Heating - 19
  mode: single
  trigger:
    # Coming home triggered
    - platform: state
      entity_id: input_boolean.home_state
      to: "on"
      # Daytime schedule started
    - platform: state
      entity_id: schedule.bedroom_daytime
      to: "on"
  condition:
    # People are home
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"
    # Daytime schedule is active
    - condition: state
      entity_id: schedule.bedroom_daytime
      state: "on"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.bedroom
      data:
        temperature: 19
