- alias: Bedroom - Heating - Home State
  mode: single

  # Home/Away state changes
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home_state

  action:
    - choose:
        # Someone arrived home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "on"
          sequence:
            - choose:
                # Daytime Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.bedroom_daytime
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 19
                      target:
                        entity_id: climate.bedroom

                # Daytime Schedule is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.bedroom_daytime
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 17
                      target:
                        entity_id: climate.bedroom

        # Everyone left home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.bedroom
