- alias: Bedroom - Heating - 17
  mode: single
  trigger:
    # Leaving home triggered
    - platform: state
      entity_id: input_boolean.home_state
      to: "off"
    # Daytime schedule ended
    - platform: state
      entity_id: schedule.bedroom_daytime
      to: "off"
  condition:
    # Daytime schedule is inactive
    - condition: state
      entity_id: schedule.bedroom_daytime
      state: "off"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.bedroom
      data:
        temperature: 17
