- alias: Dehumidifier - Bedroom - Toggle
  mode: single

  triggers:
    # Cheap Electricity boolean has a state change
    - trigger: state
      entity_id:
        - input_boolean.cheap_electricity
    # Bedroom daytime has a state change
    - trigger: state
      entity_id:
        - schedule.bedroom_daytime

  actions:
    - choose:
        # Bedroom schedule is off or electricity is expensive - turn off
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: input_boolean.cheap_electricity
                  state: "off"
                - condition: state
                  entity_id: schedule.bedroom_daytime
                  state: "off"
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.dehumidifier_bedroom_switch

        # Bedroom schedule is on, window is closed and electricity is cheap - turn on
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "on"
            - condition: state
              entity_id: schedule.bedroom_dehumidifier
              state: "on"
            - condition: state
              entity_id: binary_sensor.bedroom_window_opening
              state: "off"
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.dehumidifier_bedroom_switch
