- alias: Dehumidifier - Bedroom - Toggle
  mode: single

  trigger:
    # Cheap Electricity boolean has a state change
    - platform: state
      entity_id:
        - input_boolean.cheap_electricity
    # Time triggers at all possible wake up times in the week.
    # We check further down to see whether the dehumidifier schedule
    # is active yet on that day. Offset by 1 minute to avoid any race conditions
    - platform: time
      at: "07:01:00"
    - platform: time
      at: "07:31:00"
    - platform: time
      at: "08:31:00"

  action:
    - choose:
        # Electricity is *not* cheap
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "off"
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.dehumidifier_bedroom_switch

        # Electricity is cheap & the dehumidifier schedule is active
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "on"
            - condition: state
              entity_id: schedule.bedroom_dehumidifier
              state: "on"
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.dehumidifier_bedroom_switch
