- alias: Dehumidifier - Bedroom - Window
  mode: single

  # Window state changes
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.bedroom_window_opening

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.bedroom_window_opening
              state: "on"
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.dehumidifier_bedroom_switch

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.bedroom_window_opening
              state: "off"
          sequence:
            - choose:
                # Bedroom daytime schedule active
                - conditions:
                    - condition: state
                      entity_id: schedule.bedroom_daytime
                      state: "on"
                  sequence:
                    - action: switch.turn_on
                      target:
                        entity_id: switch.dehumidifier_bedroom_switch

                # Bedroom daytime schedule not active
                - conditions:
                    - condition: state
                      entity_id: schedule.bedroom_daytime
                      state: "off"
                  sequence:
                    - action: switch.turn_on
                      target:
                        entity_id: switch.dehumidifier_bedroom_switch
