- alias: Dehumidifier - Bedroom - Off
  mode: single
  trigger:
    - platform: state
      entity_id:
        - input_boolean.cheap_electricity
      to: "off"
    - platform: time
      at: "21:30:00"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.dehumidifier_bedroom_switch
