- alias: Dehumidifier - Bedroom - Toggle
  mode: single

  trigger:
    # Cheap Electricity boolean has a state change
    - platform: state
      entity_id:
        - input_boolean.cheap_electricity
    # Time triggers to avoid dehumidifier turning on when we're in bed
    - platform: time
      at: "08:00:00"
    - platform: time
      at: "09:00:00"

  action:
    - choose:
        # Electricity is *not* cheap
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "off"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.dehumidifier_bedroom_switch

        # Electricity is cheap & the dehumidifier schedule is active
        - conditions:
            - condition: state
              entity_id: input_boolean.cheap_electricity
              state: "on"
            - condition: state
              entity_id: schedule.bedroom_dehumidifier
              state: "on"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.dehumidifier_bedroom_switch
