- alias: Dehumidifier - Bedroom - Toggle
  mode: single

  triggers:
    # Bedroom dehumidifier schedule has a state change
    - trigger: state
      entity_id:
        - schedule.bedroom_dehumidifier
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  actions:
    - choose:
        # Bedroom dehumidifier schedule is off - turn off
        - conditions:
            - condition: state
              entity_id: schedule.bedroom_dehumidifier
              state: "off"
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.dehumidifier_bedroom_switch

        # Bedroom dehumidifier schedule is on, window is closed and electricity is cheap - turn on
        - conditions:
            - condition: state
              entity_id: schedule.bedroom_dehumidifier
              state: "on"
            - condition: state
              entity_id: binary_sensor.bedroom_window_opening
              state: "off"
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.dehumidifier_bedroom_switch
