- alias: Heating - Bedroom - Window
  mode: single

  # Window state changes
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.upstairs_windows

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "on"
          sequence:
            - action: climate.turn_off
              target:
                entity_id: climate.bedroom

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "off"
          sequence:
            - choose:
                # Bedroom daytime schedule active
                - conditions:
                    - condition: state
                      entity_id: schedule.bedroom_daytime
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.bedroom

                # Bedroom daytime schedule not active
                - conditions:
                    - condition: state
                      entity_id: schedule.bedroom_daytime
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.bedroom
