- alias: Heating - Bedroom - Schedule
  mode: single

  triggers:
    # Has the state of the schedule just changed
    - trigger: state
      entity_id:
        - schedule.bedroom_daytime
    # Has anyone just come/left home?
    - trigger: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  # Upstairs windows are closed
  condition:
    - condition: state
      entity_id: binary_sensor.upstairs_windows
      state: "off"

  action:
    - choose:
        # Daytime schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.bedroom_daytime
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 22
                      target:
                        entity_id: climate.bedroom

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.bedroom

        # Daytime schedule is not active
        - conditions:
            - condition: state
              entity_id: schedule.bedroom_daytime
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 22
              target:
                entity_id: climate.bedroom
