- alias: Lights - Bedroom - Schedule
  mode: single

  triggers:
    # Is the time 1930
    - trigger: time
      at: "19:30:00"

  # Specifically bertie or stoof are home
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.bertie
          state: home
        - condition: state
          entity_id: person.stoof
          state: home

  # Turn on bedroom lights
  action:
    - action: light.turn_on
      target:
        entity_id:
          - light.bedroom
      data:
        kelvin: 2600
        brightness_pct: 100
