- alias: Heating - Kitchen - Schedule
  mode: single

  triggers:
    # Has the state of the schedule just changed
    - trigger: state
      entity_id:
        - schedule.kitchen_daytime
        - schedule.kitchen_evening
    # Has anyone just come/left home?
    - trigger: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  action:
    - choose:
        # No one is home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.kitchen

        # Evening schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.kitchen_evening
              state: "on"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 22
              target:
                entity_id: climate.kitchen

        # Daytime schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.kitchen_daytime
              state: "on"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 21
              target:
                entity_id: climate.kitchen

      default:
        - action: climate.set_temperature
          data:
            temperature: 19
          target:
            entity_id: climate.kitchen
