- alias: Heating - Kitchen - Schedule
  mode: single

  triggers:
    # Has the state of the schedule just changed
    - trigger: state
      entity_id:
        - schedule.kitchen_evening
    # Has anyone just come/left home?
    - trigger: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  action:
    - choose:
        # Daytime schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.kitchen_evening
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.kitchen

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 19
                      target:
                        entity_id: climate.kitchen

        # Daytime schedule is not active
        - conditions:
            - condition: state
              entity_id: schedule.kitchen_evening
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 20
              target:
                entity_id: climate.kitchen
