- alias: Attic - Heating - Home State
  mode: single

  # Home/Away state changes
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home_state

  action:
    - choose:
        # Someone arrived home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "on"
          sequence:
            - choose:
                # Stoof WFH Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.attic_wfh
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.attic

                # Stoof WFH Schedule is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.attic_wfh
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 17
                      target:
                        entity_id: climate.attic

        # Everyone left home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 17
              target:
                entity_id: climate.attic
