- alias: Attic - Heating - Schedule
  mode: single

  # WFH schedule changes
  trigger:
    - platform: state
      entity_id:
        - schedule.attic_wfh

  action:
    - choose:
        # WFH schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.attic_wfh
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.study

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.study

        # WFH schedule deactivated
        - conditions:
            - condition: state
              entity_id: schedule.attic_wfh
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.study
