- alias: Heating - Attic - Schedule
  mode: single

  triggers:
    # Has the state of the schedule just changed
    - trigger: state
      entity_id:
        - schedule.attic_wfh
    # Has anyone just come/left home?
    - trigger: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - trigger: time_pattern
      minutes: /15

  action:
    - choose:
        # WFH schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.attic_wfh
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - action: climate.turn_on
                      target:
                        entity_id: climate.attic
                    - action: climate.set_temperature
                      data:
                        temperature: 21
                      target:
                        entity_id: climate.attic

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - action: climate.turn_on
                      target:
                        entity_id: climate.attic
                    - action: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.attic

        # WFH schedule is not active
        - conditions:
            - condition: state
              entity_id: schedule.attic_wfh
              state: "off"
          sequence:
            - action: climate.turn_on
              target:
                entity_id: climate.attic
            - action: climate.set_temperature
              data:
                temperature: 19
              target:
                entity_id: climate.attic
