- alias: Workstation - Attic - Schedule
  mode: single

  triggers:
    # Schedule state changes
    - trigger: state
      entity_id:
        - schedule.attic_wfh

  # Bertie is home
  condition:
    - condition: state
      entity_id: person.bertie
      state: "home"

  action:
    - choose:
        # Schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.attic_wfh
              state: "on"
          sequence:
            - action: switch.turn_on
              target:
                entity_id:
                  - switch.attic_workstation_switch

        # Schedule is *not* active
        - conditions:
            - condition: state
              entity_id: schedule.attic_wfh
              state: "off"
          sequence:
            - action: switch.turn_off
              target:
                entity_id:
                  - switch.attic_workstation_switch
