- alias: Heating - Nursery - Window
  mode: single

  # Window state changes
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.upstairs_windows

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "on"
          sequence:
            - action: climate.turn_off
              target:
                entity_id: climate.nursery

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "off"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 20
              target:
                entity_id: climate.nursery
