- alias: Heating - Downstairs - Window
  mode: single

  # Window state changes
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.living_room_window_opening

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_window_opening
              state: "on"
          sequence:
            - action: climate.set_temperature
              data:
                temperature: 5
              target:
                entity_id: climate.downstairs

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_window_opening
              state: "off"
          sequence:
            - choose:
                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.downstairs

                # Hallway Evening Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.downstairs_evening
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.downstairs

                # Hallway Daytime Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.downstairs_daytime
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 19
                      target:
                        entity_id: climate.downstairs

              default:
                - action: climate.set_temperature
                  data:
                    temperature: 18
                  target:
                    entity_id: climate.downstairs
