---
name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        shell: bash
        env: # Set the secret as an input
          HA_CONFIG_DEPLOY_URI: ${{ secrets.HA_CONFIG_DEPLOY_URI }}
        run: |
          curl -X POST "https://hooks.nabu.casa/$HA_CONFIG_DEPLOY_URI"
