name: Main

on:
  push:
    branches:
      - main

jobs:
  full_deploy:
    name: Full Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trigger Full Deploy
        shell: bash
        run: |
          curl -X POST "https://hooks.nabu.casa/${{ secrets.HA_CONFIG_DEPLOY_URI}}"
