name: Main

on:
  push:
    branches:
      - main

jobs:
  full_deploy:
    name: Full Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Trigger Full Deploy
        shell: bash
        run: |
          curl -X POST "https://hooks.nabu.casa/${{ secrets.HA_CONFIG_DEPLOY_URI}}"
