- alias: Heating - Study - Window
  mode: single

  # Window state changes
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.upstairs_windows

  action:
    - choose:
        # Window is opened
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "on"
          sequence:
            - action: climate.turn_off
              target:
                entity_id: climate.tado_trv_study

        # Window is closed
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "off"
          sequence:
            - choose:
                # Bertie WFH Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.study_wfh
                      state: "on"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 21
                      target:
                        entity_id: climate.tado_trv_study

                # Bertie WFH Schedule is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.study_wfh
                      state: "off"
                  sequence:
                    - action: climate.set_temperature
                      data:
                        temperature: 19
                      target:
                        entity_id: climate.tado_trv_study
