- alias: Lights - Study - Schedule
  mode: single

  trigger:
    - platform: state
      entity_id:
        - schedule.study_wfh

  # Someone is home
  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"

  action:
    - choose:
        # Schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.study_wfh
              state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.desk
              data:
                brightness_pct: 100

        # Schedule is *not* active
        - conditions:
            - condition: state
              entity_id: schedule.study_wfh
              state: "off"
          sequence:
            - service: light.turn_off
              target:
                entity_id:
                  - light.desk
