- alias: Study - Heating - 20
  mode: single
  trigger:
    # Coming home triggered
    - platform: state
      entity_id: input_boolean.home_state
      to: "on"
    # Study window closed
    - platform: state
      entity_id: binary_sensor.study_window_opening
      to: "off"
    # WFH schedule started
    - platform: state
      entity_id: schedule.study_wfh
      to: "on"
  condition:
    # People are home
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"
    # WFH schedule is active
    - condition: state
      entity_id: schedule.study_wfh
      state: "on"
    # Window is closed
    - condition: state
      entity_id: binary_sensor.study_window_opening
      state: "off"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.study
      data:
        temperature: 20
