- alias: Study - Heating - 18
  mode: single
  trigger:
    # Leaving home triggered
    - platform: state
      entity_id: input_boolean.home_state
      to: "off"
    # WFH schedule ended
    - platform: state
      entity_id: schedule.study_wfh
      to: "off"
    # 3 Hourly Forecast becomes "cold"
    - platform: state
      entity_id: input_boolean.three_hourly_warm
      to: "off"
  condition:
    # Window is closed
    - condition: state
      entity_id: binary_sensor.study_window_opening
      state: "off"
    # 3 Hourly Forecast is not "warm"
    - condition: state
      entity_id: input_boolean.three_hourly_warm
      state: "off"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.study
      data:
        temperature: 18
