- alias: Study - Heating - Home State
  mode: single

  # Home/Away state changes
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home_state

  # Study window is closed
  condition:
    - condition: state
      entity_id: binary_sensor.study_window_opening
      state: "off"

  action:
    - choose:
        # Someone arrived home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "on"
          sequence:
            - choose:
                # Bertie WFH Schedule is active
                - conditions:
                    - condition: state
                      entity_id: schedule.study_wfh
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.study

                # Bertie WFH Schedule is *not* active
                - conditions:
                    - condition: state
                      entity_id: schedule.study_wfh
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.study

        # Everyone left home
        - conditions:
            - condition: state
              entity_id: input_boolean.home_state
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.study
