- alias: Study - Heating - Schedule
  mode: single

  trigger:
    # Has the state of the schedule just changed
    - platform: state
      entity_id:
        - schedule.study_wfh
    # Has anyone just come/left home?
    - platform: state
      entity_id:
        - input_boolean.home_state
    # Has 15 minutes elapsed?
    - platform: time_pattern
      minutes: /15

  # Study window is closed
  condition:
    - condition: state
      entity_id: binary_sensor.study_window_opening
      state: "off"

  action:
    - choose:
        # WFH schedule activated
        - conditions:
            - condition: state
              entity_id: schedule.study_wfh
              state: "on"
          sequence:
            - choose:
                # Someone is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "on"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 20
                      target:
                        entity_id: climate.study

                # No one is home
                - conditions:
                    - condition: state
                      entity_id: input_boolean.home_state
                      state: "off"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        temperature: 18
                      target:
                        entity_id: climate.study

        # WFH schedule deactivated
        - conditions:
            - condition: state
              entity_id: schedule.study_wfh
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 18
              target:
                entity_id: climate.study
