- alias: Workstation - Study - Schedule
  mode: single

  triggers:
    # Schedule state changes
    - trigger: state
      entity_id:
        - schedule.study_wfh

  # Bertie is home
  condition:
    - condition: state
      entity_id: person.bertie
      state: "home"

  action:
    - choose:
        # Schedule is active
        - conditions:
            - condition: state
              entity_id: schedule.study_wfh
              state: "on"
          sequence:
            - action: switch.turn_on
              target:
                entity_id:
                  - switch.study_workstation_switch
            - action: light.turn_on
              target:
                entity_id: light.desk
              data:
                brightness_pct: 100

        # Schedule is *not* active
        - conditions:
            - condition: state
              entity_id: schedule.study_wfh
              state: "off"
          sequence:
            - action: switch.turn_off
              target:
                entity_id:
                  - switch.study_workstation_switch
            - action: light.turn_off
              target:
                entity_id:
                  - light.desk
