- alias: Workstation - On
  mode: single
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: state
      entity_id: schedule.study_wfh
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.study_workstation_switch
